language: node_js
node_js:
  - "6.9.0"
before_install:
  - sudo apt-get install libblas-dev
env:
  global:
    - CXX=g++-4.8
    - CC_TEST_REPORTER_ID=3723d8c83fad0d62970815c780582596b434c352fc64f6b6b3d72599540fb997
before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
